name: release

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  release-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> "$GITHUB_OUTPUT"
        id: extract_branch

      - name: Checkout
        id: checkout
        uses: https://code.forgejo.org/actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Generate release with changelog
        uses: https://git.h.oluflorenzen.de/finkregh/actions/actions/release-with-cog@f44f30a0f1b34eaf5faec16f1bd796b3a12c71fe # 3.4.1
        with:
          cog_changelog_args_pr: '--unified'
